### ISSUE TITLE
Relacion de funciones y plano cartesiano

### ISSUE THREAD

**Issue by Alondra-oss** [SistemasTecTlaxiaco/practica-6-relaciones-funciones-y-plano-cartesiano-team-sael-1as#1]
[practica 3 plano cartesiano..-.pdf](https://github.com/user-attachments/files/17164622/practica.3.plano.cartesiano.-.pdf)

**Comment by YulianaMorales18** [comment]
Portada 25/25
Procedimiento 25/25
Figuras, ilustraciones y fotografías. 25/25
Resultados y conclusiones 25/25
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
